package expression;

import org.antlr.v4.runtime.*;
import org.antlr.v4.runtime.tree.*;
import org.antlr.v4.runtime.CharStreams;

import java.io.IOException;

public class main {
    public static void main(String[] args) throws IOException {

        // we expect exactly one argument: the name of the input file
        /*if (args.length != 1) {
            System.err.println("\n");
            System.err.println("Impl Interpreter\n");
            System.err.println("=================\n\n");
            System.err.println("Please give as input argument a filename\n");
            System.exit(-1);
        }*/
        String filename = "C:\\Users\\siggo\\IdeaProjects\\CompilerTek\\untitled\\src\\main\\java\\expression\\02-trafiklys-minimal.txt";

        // open the input file
        CharStream input = CharStreams.fromFileName(filename);
        //new ANTLRFileStream (filename); // depricated

        // create a lexer/scanner
        hardwareLexer lex = new hardwareLexer(input);

        // get the stream of tokens from the scanner
        CommonTokenStream tokens = new CommonTokenStream(lex);

        // create a parser
        hardwareParser parser = new hardwareParser(tokens);

        // and parse anything from the grammar for "start"
        ParseTree parseTree = parser.start();

        // Construct an interpreter and run it on the parse tree
        Interpreter interpreter = new Interpreter();
        AST result = interpreter.visit(parseTree);
        System.out.println("Getting to result");
        //System.out.println("The result is: " + result.eval());
    }
}

// We write an interpreter that implements interface
// "implVisitor<T>" that is automatically generated by ANTLR
// This is parameterized over a return type "<T>" which is in our case
// simply a Integer.

class Interpreter extends AbstractParseTreeVisitor<AST> implements hardwareVisitor<AST> {
    Environment env = new Environment();


    @Override
    public AST visitStart(hardwareParser.StartContext ctx) {
        return null;
    }

    @Override
    public AST visitNot(hardwareParser.NotContext ctx) {
        return new Not((Expr) visit(ctx.ex1));
    }

    @Override
    public AST visitOr(hardwareParser.OrContext ctx) {
        return new Or((Expr) visit(ctx.ex1), (Expr) visit(ctx.ex2));
    }

    @Override
    public AST visitParanthesis(hardwareParser.ParanthesisContext ctx) {
        return null;
    }

    @Override
    public AST visitAnd(hardwareParser.AndContext ctx) {
        return new And((Expr) visit(ctx.ex1), (Expr) visit(ctx.ex2));
    }

    @Override
    public AST visitBinexpr(hardwareParser.BinexprContext ctx) {
        Variable var= new Variable(ctx.id.getText());
        var.eval(env);
        return var;
    }

    @Override
    public AST visitUpdateVal1(hardwareParser.UpdateVal1Context ctx) {
        return null;
    }

    @Override
    public AST visitLatch1(hardwareParser.Latch1Context ctx) {
        return null;
    }

    @Override
    public AST visitSimulate1(hardwareParser.Simulate1Context ctx) {
        return null;
    }
}

